version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: .ci/Dockerfile
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    expose:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: .ci/Dockerfile
    container_name: react-frontend
    ports:
      - '3001:80'
    depends_on:
      - backend

# volumes:
#   frontend-build:
