version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: .ci/Dockerfile
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: .ci/Dockerfile
  #   container_name: react-builder
  #   volumes:
  #     - ./frontend/build:/app/build
  #   depends_on:
  #     - backend

  nginx:
    build:
      context: ./frontend
      dockerfile: .ci/Dockerfile
    container_name: nginx-server
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - backend

# volumes:
#   frontend-build:
