FROM node:18

WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
# COPY package*.json ./

# Install dependencies
# RUN npm install

# Copy the rest of the application code to the working directory
# COPY . .

EXPOSE 3001

CMD [ "npm", "run", "start" ]